FROM python:3.12

RUN apt-get update && apt-get install -y \
    libsasl2-dev \
    python3-dev \
    libldap2-dev \
    libssl-dev \
    libffi-dev \
    openssl \
    dnsutils

WORKDIR ar_api

COPY requirements.txt .

RUN pip install -r requirements.txt
ENV OPENSSL_LEGACY_SERVER_CONNECT=1

ADD main.py .

CMD ["python3", "-m", "main", "run", "--host=0.0.0.0"]
